name: Speech-to-Text and Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and Unzip Model
        run: |
          wget -O vosk-server/models/model.zip https://alphacephei.com/vosk/models/vosk-model-small-fa-0.5.zip
          unzip vosk-server/models/model.zip -d vosk-server/models
          # mv vosk-server/models/vosk-model-small-fa-0.5/ vosk-server/models/vosk-model-fa-0.5/

      - name: Run ASR Server
        run: |
          python vosk-server/websocket/asr_server.py &
          echo "ASR Server is running in the background."

      - name: Wait for ASR Server
        run: |
          until nc -z localhost 2700; do
            echo "Waiting for ASR Server..."
            sleep 1
          done

      - name: Run Bot
        run: python bot2.py
        env:
          BOT_TOKEN: ${{ env.BOT_TOKEN }}
