name: Speech-to-Text and Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and Unzip Model
        run: |
          cd vosk-server/websocket/models/
          gdown 1Dvk4Cj_IK5O7OseWPjMSplU70C8KW9XD
          unzip vosk-model-small-fa-0.5

      - name: Run ASR Server
        run: |
          cd vosk-server/websocket/
          python asr_server.py &
          echo "ASR Server is running in the background."

      - name: Wait for ASR Server
        run: |
          until nc -z localhost 2700; do
            echo "Waiting for ASR Server..."
            sleep 1
          done

      - name: Run Bot
        run: python bot2.py
        env:
          BOT_TOKEN: ${{ env.BOT_TOKEN }}
